name: Reusable Workflow

on: 
  workflow_call:
    secrets:
      PRIVATE_NUGET_USERNAME:
        required: true
      PRIVATE_NUGET_TOKEN:
        required: true

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }} 
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
         
      - name: Clean
        run: dotnet clean

      - name: Add private nuget source 
        run: dotnet nuget add source https://nuget.pkg.github.com/${{ secrets.PRIVATE_NUGET_USERNAME }}/index.json -n github -u ${{ secrets.PRIVATE_NUGET_USERNAME }} -p ${{ secrets.PRIVATE_NUGET_TOKEN }} --store-password-in-clear-text
      
      - name: list
        run: dotnet nuget list source

      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
  
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      
      - name: Add private nuget source
        run: dotnet nuget add source https://nuget.pkg.github.com/${{ secrets.PRIVATE_NUGET_USERNAME }}/index.json -n github -u ${{ secrets.PRIVATE_NUGET_USERNAME }} -p ${{ secrets.PRIVATE_NUGET_TOKEN }} --store-password-in-clear-text
                
      - name: Install dependencies
        run: dotnet restore
        
      - name: Run tests
        run: dotnet test --no-restore --verbosity normal
