name: Version build and test

on:
  push:
    branches: [ main ]

jobs:
  versioning:
    name: 'Versioning'
    runs-on: ubuntu-latest
    outputs:
      previous-version: ${{ steps.get-version.outputs.previous-version }}
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0
          
      - name: Git version
        id: get-version
        uses: codacy/git-version@2.4.0
        with:
          release-branch: main
          prefix: v

      - name: Tag commit
        run: |
          git tag ${{ steps.get-version.outputs.version }} ${{ github.sha }}
          git push origin ${{ steps.get-version.outputs.version }}

  build-and-test:
    uses: ./.github/workflows/build-test-reusable.yml 
    needs: versioning
    secrets:
      NUGET_USERNAME: ${{ secrets.PRIVATE_NUGET_USERNAME }}
      NUGET_TOKEN: ${{ secrets.PRIVATE_NUGET_TOKEN }}
